### PR TITLE
Add support for empty `separator`

### LINKED ISSUE #52: Allow empty replacement
My use case is create usernames without separator.
Following the documentation: https://github.com/sindresorhus/slugify#separator

I have tried with:

```
slugify('BAR and baz', {separator: ''});
```

And I expect this:

```
'barandbaz'
```

But I get an error:

```
SyntaxError: Invalid regular expression: /{2,}/: Nothing to repeat
```

### PR DESCRIPTION
**Pull request by Arnovsky**
Fixes #52

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think it should be explicitly documented as it's not immediately obvious that it's supported. Could add another example (in readme and index.d.ts).

**Comment by Arnovsky** [comment]
CI seems to failing due to an unrelated issue, something with `transliterate` breaking with version `0.1.1` [in this commit],(https://github.com/sindresorhus/transliterate/commit/5258c74e9c157516ab6ca1ab7f4650aa74df8c1d) I have change the tests accordingly.

**Comment by Arnovsky** [comment]
@sindresorhus Is the documentation added OK?

**Comment by sindresorhus** [comment]
👍🏻

**Pull request merged**
